afristyle/__init__.py
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from afristyle import config
from flask import Flask
from flask_marshmallow import Marshmallow


db = SQLAlchemy()
ma = Marshmallow()

def create_app():
  
  app = Flask(__name__, template_folder='templates', static_folder='static')
  CORS(app)
  
  # db_config = {
  #   'host': 'localhost',
  #   'user': 'postgres',
  #   'password': '10322',
  #   'database': 'blogBd',
  #   'port': '5432'
  # }
  
  # Connexion distante
  db_config = {
      'host': 'dpg-cnug8dcf7o1s739nt43g-a.frankfurt-postgres.render.com',
      'user': 'blogbd_v1wk_user',
      'password': 'JS6xPYO45MU4N9SHOSW2Yw6PQkDjKWQ1',
      'database': 'blogbd_v1wk',
      'port': '5432'
  }
  
  # db_config = {
  #   'host': 'localhost',
  #   'user': 'root',
  #   'password': '',
  #   'database': 'blogbd',
  # }

  app.config['SECRET_KEY'] = config.SECRET_KEY
  #Charger les configurations à partir de l'objet config
  app.config.from_object(config)
  app.config['imagesPath'] = 'afristyle/static/images'

  # app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+pymysql://{db_config['user']}:{db_config['password']}@{db_config['host']}/{db_config['database']}"
  app.config['SQLALCHEMY_DATABASE_URI'] = f"postgresql+psycopg2://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}"
  
  # Initialiser la base de données
  db.init_app(app)
  ma.init_app(app)
  
  with app.app_context():
    
    
    from afristyle.main.main import main
    from afristyle.articles.routes import article
    from afristyle.utilisateur.routes import user
    from afristyle.categories.routes import category
    
    app.register_blueprint(main)
    app.register_blueprint(article)
    app.register_blueprint(user)
    app.register_blueprint(category)
    
    db.create_all()
    
  return app 

afristyle/articles/__init__.py
from .model import Article

afristyle/articles/routes.py
import os
from flask import Blueprint, app, render_template, current_app
from flask import request
from afristyle import db
from afristyle.articles import Article
from flask import jsonify
from afristyle.articles.mashmallw import Mashmallow
from sqlalchemy.exc import SQLAlchemyError



article = Blueprint('article', __name__)

@article.route("/article/<article_id>", methods=["GET"])
def getarticle(article_id):
    try:
        article = Article.query.filter_by(id=article_id).first()
        if article_id:
            article_mash = Mashmallow(many=False)
            article_data = article_mash.dump(article)
            return render_template("article.html", article_data=article_data)
        else:
            return jsonify(message = 'article introuvable')
    except SQLAlchemyError as e :
       return jsonify(message='erreur lors du traitement de votre requête')
    

@article.route("/nouvelle_article")
def redaction():
    return render_template("redaction.html")

@article.route("/savearticle", methods=["POST"])
def savearticle():
  category = request.form.get('category')
  title = request.form.get('title')
  description = request.form.get('description')
  filename = request.form.get('path')
  contenu = request.form.get('contenu')
  image = request.files['image']

  # Create a new Article instance
  article = Article(
      categorie=category,
      titre=title,
      contenu=contenu,
      image_principale=filename,
      description = description
  )

  # Save the article to the database
  db.session.add(article)
  db.session.commit()
  
  # Save the image to the specified path
  images_path = current_app.config['imagesPath']
  image.save(os.path.join(images_path, filename))


  return jsonify(message= "Article enregistré avec succès!")


@article.route("/delete/<int:article_id>", methods=["DELETE"])
def delete_article(article_id):
    try:
        article = Article.query.get(article_id)
        if article:
            db.session.delete(article)
            db.session.commit()
            return jsonify(message="Article deleted successfully"), 200
        else:
            return jsonify(message="Article not found"), 404
    except Exception as e:
        return jsonify(message="Error deleting article: " + str(e)), 500

afristyle/categories/routes.py
from flask import Blueprint, render_template
from afristyle.articles.mashmallw import Mashmallow
from afristyle.articles.model import Article



category = Blueprint('category', __name__)

@category.route("/article_by_category/<category>")
def article_by_category(category):
  # Récupérer les 6 premiers articles triés par date de création décroissante
  articles = Article.query.order_by(Article.date_publication.desc()).all()
  
  mashmallow_article = Mashmallow(many=True)
  article_data = mashmallow_article.dump(articles)
  
  return render_template("category.html", articles = article_data , categorie= category )

afristyle/main/main.py
from flask import Blueprint, render_template

from afristyle.articles.model import Article
from afristyle.articles.mashmallw import Mashmallow


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/index")
def home():
    # Récupérer les 6 premiers articles triés par date de création décroissante
    articles = Article.query.order_by(Article.date_publication.desc()).limit(9).all()
    
    mashmallow_article = Mashmallow(many=True)
    article_data = mashmallow_article.dump(articles)
    
    if(len(article_data)):
         return render_template("index.html", articles = article_data )
    else:
         return render_template("index.html")

@main.route("/register")
def register():
    return render_template("login/register.html")

afristyle/utilisateur/__init__.py
from .model import User

afristyle/utilisateur/routes.py
from flask import Blueprint, render_template


user = Blueprint('user', __name__)

@user.route("/connexion")
def home():
    return render_template("index.html")

@user.route("/liste")
def register():
    return render_template("login/register.html")

afristyle/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/favicon.ico">
<link rel="icon" type="image/png" href="./assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<title>Mundana Template by WowThemesNet</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,700" rel="stylesheet">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- Main CSS -->
<link href="./assets/css/main.css" rel="stylesheet"/>
</head>
<body>
<!--------------------------------------
NAVBAR
--------------------------------------->
<nav class="topnav navbar navbar-expand-lg navbar-light bg-white fixed-top">
<div class="container">
	<a class="navbar-brand" href="./index.html"><strong>Mundana</strong></a>
	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="navbar-collapse collapse" id="navbarColor02" style="">
		<ul class="navbar-nav mr-auto d-flex align-items-center">
			<li class="nav-item">
			<a class="nav-link" href="./index.html">Intro <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Culture</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Tech</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Politics</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Health</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Collections</a>
			</li>            
			<li class="nav-item">
			<a class="nav-link" href="./about.html">About</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./docs.html">Template <span class="badge badge-secondary">docs</span></a>
			</li>
		</ul>
		<ul class="navbar-nav ml-auto d-flex align-items-center">
			<li class="nav-item highlight">
			<a class="nav-link" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Get this Theme</a>
			</li>
		</ul>
	</div>
</div>
</nav>
<!-- End Navbar -->
    
    
<!--------------------------------------
HEADER
--------------------------------------->
<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
					<p class="text-uppercase font-weight-bold">
						<a class="text-danger" href="#">Templates</a>
					</p>
					<h1 class="display-4 secondfont mb-3 font-weight-bold">Mundana - Bootstrap 4 HTML Template for Professional Blogging</h1>
					<p class="mb-3">
						 Here we're introducing you what you can do with Mundana theme.
					</p>
					<div class="d-flex align-items-center">
                        <a target="_blank" href="https://www.buymeacoffee.com/sal"><img class="rounded-circle" src="assets/img/demo/sal.jpg" width="70"></a>
                        <small class="ml-2"><a target="_blank" href="https://www.buymeacoffee.com/sal">Sal</a> <span class="text-muted d-block">A few hours ago &middot; 5 min. read</span>
						</small>
					</div>
				</div>
				<div class="col-md-6 pr-0">
					<img src="./assets/img/screenshot-mundana.png" class="shadow">
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Header -->
    
<!--------------------------------------
MAIN
--------------------------------------->    
<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
		<div class="col-lg-2 pr-4 mb-4 col-md-12 text-center">
			<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
				<div class="share d-inline-block">
					<!-- AddToAny BEGIN -->
					<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
						<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
						<a class="a2a_button_facebook"></a>
						<a class="a2a_button_twitter"></a>
					</div>
					<script async src="https://static.addtoany.com/menu/page.js"></script>
					<!-- AddToAny END -->
				</div>
			</div>
		</div>
		<div class="col-md-12 col-lg-8">
			<article class="article-post">
			<p>
                I hope you like Mundana. My name is <a target="_blank" href="https://www.buymeacoffee.com/sal">Sal</a>, I am the author of this template that I'm sharing you for free. You are currently previewing its demo, the article template to be more specific.
			</p>
			<p>
				 Here are a few screenshots of Mundana and what you can do with it.
			</p>
			<p>
				<a href="./article.html"><img src="assets/img/screenshot-mundana-article.png" class="shadow"></a>
			</p>
			<p>
				<a href="./index.html"><img src="assets/img/screenshot-mundana.png" class="shadow"></a>
			</p>
			<p>
				<a href="./category.html"><img src="assets/img/screenshot-mundana-category.png" class="shadow"></a>
			</p>
			<p>
				 Like it? You can download Mundana HTML Template for free!
			</p>
			<p>
				<a target="_blank" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template" class="btn btn-secondary">&rarr; Go to Mundana's download page</a>
			</p>
			</article>
			<div class="border p-5 bg-lightblue mt-5">
				<div class="row justify-content-between align-items-center">
					<div class="col-md-8 mb-2 mb-md-0">
						<h5 class="font-weight-bold mb-3">About the author of Mundana</h5>
						 Hi, I'm Sal, the author of the template you're currently previewing. I am sharing for free, for your personal &amp; commercial use on unlimited domains. If you'd like to support my work, donations are highly appreciated! You can remove the credit links after donation. Thank you!
					</div>
					<div class="col-md-4">
						<a target="_blank" href="https://www.buymeacoffee.com/sal" class="btn btn-warning btn-block"><i class="fa fa-coffee"></i> Buy me a coffee</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
    
<div class="container pt-4 pb-4">
	<h5 class="font-weight-bold spanborder"><span>Read next</span></h5>
	<div class="row">
		<div class="col-lg-6">
			<div class="card border-0 mb-4 box-shadow h-xl-300">
				<div style="background-image: url(./assets/img/demo/3.jpg); height: 150px; background-size: cover; background-repeat: no-repeat;">
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					<a class="text-dark" href="#">Brain Stimulation Relieves Depression Symptoms</a>
					</h2>
					<p class="card-text">
						 Researchers have found an effective target in the brain for electrical stimulation to improve mood in people suffering from depression.
					</p>
					<div>
						<small class="d-block"><a class="text-muted" href="./author.html">Favid Rick</a></small>
						<small class="text-muted">Dec 12 · 5 min read</small>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="flex-md-row mb-4 box-shadow h-xl-300">
				<div class="mb-3 d-flex align-items-center">
					<img height="80" src="./assets/img/demo/blog4.jpg">
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="./article.html">Nasa's IceSat space laser makes height maps of Earth</a>
						</h2>
						<div class="card-text text-muted small">
							 Jake Bittle in LOVE/HATE
						</div>
						<small class="text-muted">Dec 12 · 5 min read</small>
					</div>
				</div>
				<div class="mb-3 d-flex align-items-center">
					<img height="80" src="./assets/img/demo/blog5.jpg">
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="./article.html">Underwater museum brings hope to Lake Titicaca</a>
						</h2>
						<div class="card-text text-muted small">
							 Jake Bittle in LOVE/HATE
						</div>
						<small class="text-muted">Dec 12 · 5 min read</small>
					</div>
				</div>
				<div class="mb-3 d-flex align-items-center">
					<img height="80" src="./assets/img/demo/blog6.jpg">
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="./article.html">Sun-skimming probe starts calling home</a>
						</h2>
						<div class="card-text text-muted small">
							 Jake Bittle in LOVE/HATE
						</div>
						<small class="text-muted">Dec 12 · 5 min read</small>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Main -->
    
<!--------------------------------------
FOOTER
--------------------------------------->
<div class="container mt-5">
	<footer class="bg-white border-top p-3 text-muted small">
	<div class="row align-items-center justify-content-between">
		<div>
            <span class="navbar-brand mr-2"><strong>Mundana</strong></span> Copyright &copy;
			<script>document.write(new Date().getFullYear())</script>
			 . All rights reserved.
		</div>
		<div>
			Made with <a target="_blank" class="text-secondary font-weight-bold" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Mundana Theme</a> by WowThemes.net.
		</div>
	</div>
	</footer>
</div>
<!-- End Footer -->
    
<!--------------------------------------
JAVASCRIPTS
--------------------------------------->
<script src="./assets/js/vendor/jquery.min.js" type="text/javascript"></script>
<script src="./assets/js/vendor/popper.min.js" type="text/javascript"></script>
<script src="./assets/js/vendor/bootstrap.min.js" type="text/javascript"></script>
<script src="./assets/js/functions.js" type="text/javascript"></script>
</body>
</html>

afristyle/templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<link rel="apple-touch-icon" sizes="76x76" href="../static/assets/img/a.png">
<link rel="icon" type="image/png" href="../static/assets/img/a.png">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<title>AfriStyle - article</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,700" rel="stylesheet">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- Main CSS -->
<link href="../static/assets/css/main.css" rel="stylesheet"/>
</head>

<body>
<!--------------------------------------
NAVBAR
--------------------------------------->
{% include "navbar.html" %} {% block content %}
<!-- End Navbar -->
    
<!--------------------------------------
HEADER
--------------------------------------->
<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
					<h1 class="display-4 secondfont mb-3 font-weight-bold">{{article_data.titre}}</h1>
					<p class="mb-3">
						{{article_data.description}}
					</p>
					<div class="d-flex align-items-center">
						<small class="ml-2">{{article_data.date_publication}}</span>
						</small>
					</div>
				</div>
				<div class="col-md-6 pr-0">
					<img src="../static/images/{{article_data.image_principale}}">
				</div>
				<div style="padding: 1em; text-align: justify; font-size: 22px;" data-contenu="{{article_data.contenu}}" id="article-post" class="article-post">
					
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Header -->
    
<!--------------------------------------
MAIN
--------------------------------------->
    

    
<!--------------------------------------
FOOTER
--------------------------------------->
<div class="container mt-5">
	<footer class="bg-white border-top p-3 text-muted small">
	<div class="row align-items-center justify-content-between">
		<div>
			<span class="navbar-brand mr-2"><strong>AfriStyle</strong></span> Copyright &copy;
			<script>document.write(new Date().getFullYear())</script>
			 . All rights reserved.
		</div>
	</div>
	</footer>
</div>
<!-- End Footer -->
    
<!--------------------------------------
JAVASCRIPTS
--------------------------------------->

<script>
 const articleContent = document.getElementById('article-post').getAttribute('data-contenu');
 document.getElementById('article-post').innerHTML = articleContent;
</script>
<script src="../static/assets/js/vendor/jquery.min.js" type="text/javascript"></script>
<script src="../static/assets/js/vendor/popper.min.js" type="text/javascript"></script>
<script src="../static/assets/js/vendor/bootstrap.min.js" type="text/javascript"></script>
<script src="../static/assets/js/functions.js" type="text/javascript"></script>
{% endblock %}
</body>
</html>

afristyle/templates/navbar.html
<nav class="topnav navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('main.home') }}"><strong>AfriStyle</strong></a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto d-flex align-items-center">
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.home') }}">Intro <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('category.article_by_category', category='vêtements') }}">Vêtements</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('category.article_by_category', category='chaussures') }}">Chaussures</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('category.article_by_category', category='accessoires') }}">Accéssoires</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('category.article_by_category', category='coiffure') }}">Coiffures</a>
          </li>           
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('category.article_by_category', category='musique') }}">Musique </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('category.article_by_category', category='art') }}">Art</a>
          </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{{ url_for('category.article_by_category', category='apropos') }}">A propos de nous </a>
        </li> -->
      </ul>
      <div>
        <button type="button" class="click btn btn-outline-secondary">Ecrire</button>
      </div>
    </div>
  </div>
  </nav>


  <script>
	// Récupérer tous les boutons "Lire plus"
	const buttons = document.querySelectorAll('.click');

	// Ajouter un gestionnaire d'événements click à chaque bouton
	buttons.forEach(button => {
			button.addEventListener('click', () => {

					window.location = "{{ url_for('article.redaction') }}"
			});
	});
  </script>
  

afristyle/templates/redaction.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="76x76" href="./static/assets/img/a.png">
    <link rel="icon" type="image/png" href="./static/assets/img/a.png">
    <link href="../static/assets/css/main.css" rel="stylesheet" />
    <link href="../static/assets/css/style.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <title>AfriStyle - redaction</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">
      <div class="left-section">
        <div id="papier" class="article-post">
          <div  id="paragraphs"></div>
        </div>
        <button style="background-color: #212529" id="addParagraphBtn">
          Ajouter un paragraphe
        </button>
        <button style="background-color: #212529" id="publishBtn">
          Publier
        </button>
      </div>
      <div class="right-section">
        <h2>Paramètres</h2>
        <label for="title">Titre :</label>
        <input type="text" id="title" /><br /><br />
        <label for="description">Description :</label>
        <textarea
          name="description"
          id="description"
          cols="30"
          rows="3"
        ></textarea>
        <label for="category">Catégorie :</label>
        <select id="category" class="form-select" aria-label="Catégorie">
          <option selected disabled>Choisissez une catégorie</option>
          <option value="musique">Musique</option>
          <option value="accessoires">Accessoires</option>
          <option value="vêtements">Vêtements</option>
          <option value="chaussures">Chaussures</option>
          <option value="art">Art</option>
          <option value="coiffure">Coiffure</option>
        </select>
        <label for="image">Image principale :</label>
        <input type="file" id="image" /><br /><br />
      </div>
    </div>

    <script>
      // Fonction pour ajouter un paragraphe dynamiquement
      function addParagraph() {
        const papier = document.getElementById("papier")

        // Créer un élément div pour le paragraphe
        const paragraph = document.createElement('div');
        paragraph.classList.add('paragraph');
        papier.appendChild(paragraph)


        // Créer un élément p pour la saisie du contenu
        const paragraphContent = document.createElement('p');
        paragraphContent.classList.add('paragraph-content');
        paragraphContent.contentEditable = true; // Permet l'édition du contenu

        // Ajouter le contenu par défaut au paragraphe
        paragraphContent.textContent = 'Saisir ici';

        // Ajouter le paragraphe à la zone de paragraphes
        paragraph.appendChild(paragraphContent);


        // Ajouter le paragraphe à la zone de paragraphes
        const paragraphsContainer = document.getElementById('paragraphs');
        paragraphsContainer.appendChild(paragraph);
      }

      // Écouter l'événement "click" sur le bouton "Ajouter un paragraphe"
      document.getElementById('addParagraphBtn').addEventListener('click', addParagraph);
      document.getElementById('publishBtn').addEventListener('click', saveArticle);


      function getPaperContent() {
        // Récupérer l'élément papier
        const papier = document.getElementById('papier');

        // Créer un clone de l'élément papier
        const papierClone = papier.cloneNode(true);

        // Supprimer l'attribut contenteditable de tous les descendants de papierClone
        const allEditableElements = papierClone.querySelectorAll('[contenteditable]');
        for (const element of allEditableElements) {
          element.removeAttribute('contenteditable');
        }

        // Convertir l'élément DOM en une chaîne de caractères HTML
        const contenuHTML = papierClone.outerHTML;

        return contenuHTML
      }

      function showSuccessToast(message) {
            toastr.success(message);
        }
      function showErrorToast(message){
          toastr.error(message);
      }

      function saveArticle() {

        const category = document.getElementById('category').value;
        const title = document.getElementById('title').value;
        const description = document.getElementById('description').value;
        const image = document.getElementById('image').files[0];
        const imageName = image.name;
        const contenu = getPaperContent();


        const formData = new FormData();
        formData.append('category', category);
        formData.append('title', title);
        formData.append('description', description);
        formData.append('path', imageName);  // Assuming image upload
        formData.append('contenu', contenu);
        formData.append('image', image);

        console.log(imageName);

        fetch("{{ url_for('article.savearticle')}}", {
          method: 'POST',
          body: formData,
        })
        .then(response => {
          if(!response.ok){
            showErrorToast("Erreur lors de la création ")
          }else{

            showSuccessToast("L'article a été bien enregistré !")
            // Vider les champs de saisie
            document.getElementById('title').value = '';
            document.getElementById('description').value = '';
            document.getElementById('category').selectedIndex = 0; // Réinitialiser le menu déroulant

            // Vider la zone de saisie de l'image
            document.getElementById('image').value = '';

            // Vider le contenu de la zone de texte 'paragraphs'
            document.getElementById('paragraphs').innerHTML = '';
          }
        })
        .catch(error => {
        console.error('Erreur lors de la récupération des données:', error.message);
        });
      }
    </script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  </body>
</html>